config/routes.rb
Rails.application.routes.draw do

  resources :cards

  resources :academic_years
  resources :members
  resources :covers
  resources :locations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  root "members#new"
  get 'student/select-list', to: 'student#index' , as: :select_student_list
  post 'student/select-list', to: 'student#select_student_list', as: :student_list
  get 'student/select-student', to: 'student#index'
  post 'student/select-student', to: 'student#select_student',as: :select_student
  post 'student/mark-printed', to: 'student#mark_printed',as: :mark_printed
  get 'student/new_student_list'
  post 'student/create_student_list', as: :create_student_list

  get 'card', to: 'cards#edit' , as: :edit_card_details
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  skip_before_action :verify_authenticity_token
  require 'csv'
  require 'creek'
  require 'zip'
  require 'fileutils'
  before_action :set_card, only: %i[index select_student_list select_student ]



  def index
    @students = {}
  end

  # GET /members/new
  def new_student_list

  end

  def create_student_list
    file = params[:file]
    return redirect_to student_new_student_list_path, notice: "CSV files only" unless
      file.content_type == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"




    folder_name = params[:uploaded_file].original_filename.split(".").first
    Zip::File.open(params[:uploaded_file]) do |zip_file|
        zip_file.each do |f|

          f_path = File.join("public", f.name)
          FileUtils.mkdir_p(File.dirname(f_path))
          zip_file.extract(f, f_path) unless File.exist?(f_path)
        end
    end

    cover = Cover.find_by(name: "Student").id

    creek = Creek::Book.new(file)
    sheet = creek.sheets[0]
    sheet.rows.each do |row|
      user_hash = {}
      student_academic_year_hash = {}
      user_hash[:first_name] = row.values[0]
      user_hash[:last_name] = row.values[1]
      user_hash[:membership_number] = "#{row.values[2]}-#{row.values[3]}-#{row.values[4]}-00"
      user_hash[:date_of_birth] = row.values[5]
      user_hash[:date_joined] = "02/02/2024"
      user_hash[:cover_id] = cover
      user_hash[:location_id] = student_academic_year_hash[:location_id] =  params[:location]
      student_academic_year_hash[:academic_year_id] = params[:academic_year]

      image_with_extention = Dir.entries("public/#{folder_name}").select { |f| f.include? "#{row.values[6]}" }[0]
      File.open(File.join("public/#{folder_name}", image_with_extention), 'r') do |f|
        user_hash[:image] = f
        member = Member.create(user_hash)
        student_academic_year_hash[:member_id] = member.id
        StudentAcademicYear.create(student_academic_year_hash)

      end
    end
    FileUtils.rm_rf("public/#{folder_name}")
  end

  def select_student_list

    @students = StudentAcademicYear.where(academic_year_id:params[:academic_year], location_id:params[:location])
    render :index
  end

  def select_student

    respond_to do |format|
      @student = StudentAcademicYear.find_by(member_id:params[:id])
      #setting student id and corresponding index on UI student list into session cookie to be accessed in AJAX call

      session[:student] = @student.member_id
      session[:index] = params[:index]
      #@students = StudentAcademicYear.where(academic_year_id:@student.academic_year_id,location_id:@student.location_id)
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(:card_section , partial:"members/card_section" ,locals:{ member: @student.member, card: @card} )
      end
      format.html { render :index }
    end
  end

  def mark_printed
    puts session.to_hash
    puts params

    member = Member.find(session[:student])
    member.card_printed = true
    member.save
    @student = StudentAcademicYear.find_by(member_id: session[:student])


    respond_to do |format|

      format.turbo_stream do
        render  turbo_stream: turbo_stream.replace(:"student_#{@student.member_id}" ,
          partial: 'student', locals: { student: @student, index: session[:index], fade_in: true } )
      end

      format.html { render :index }
    end

  end


  private
  # Use callbacks to share common setup or constraints between actions.

  def set_card
    @card = Card.first()
  end

end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/_student.html.erb
<% if fade_in    %>
    <tr class= "student-highlight" id = "student_<%=student.member.id %>">
<% else %>
    <tr id = "student_<%=student.member.id %>">
<% end %>
    <td><%= index.to_i+1 %></td>
    <td><%= student.member.first_name %></td>
    <td><%= student.member.last_name %></td>
    <td><%= student.member.membership_number %></td>
    <td><%= student.member.date_of_birth %></td>
    <td class="d-flex">

        <% if student.member.card_printed %>
            <%= button_to select_student_path(),params:{id: student.member.id, index: index }, class:"btn btn-outline-primary student-select mx-1" do %>
                <i class="fa fa-print mb-3"></i>
            <% end %>
        <% else%>
            <%= button_to select_student_path(),params:{id: student.member.id,index: index}, class:"btn btn-outline-danger student-select mx-1", data: {turbo_stream: true} do %>
                <i class="fa fa-print mb-3"></i>
            <% end %>
        <% end %>

        <%= link_to  edit_member_path(student.member.id), class:"btn btn-outline-dark student-select", data: {turbo_stream: true} do %>
                <i class="fa fa-edit mb-3"></i>
        <% end %>

    </td>
</tr>

app/views/student/index.html.erb
<div class="row main-section dashboard">

  <!-- Left side columns -->
    <div class="col-lg-7 left-column">
        <div class="row">
        <!-- Revenue Card -->
            <div class="col-md-12">
                <div class="card info-card revenue-card">
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center mb-0">Datatables</h5>
                    <nav>
                        <%= form_with url: student_list_path,  method: :post do |form| %>
                            <ol class="breadcrumb">

                                <li class="breadcrumb-item">
                                    <%= form.label :name , 'UNIVERSITY:' %>
                                    <%= form.select :location,
                                    options_for_select((Location.all).to_a.map{ |val| [val.name,val.id] }) %>
                                </li>
                                <li class="breadcrumb-item">
                                    <%= form.label :location , 'YEAR:' %>
                                    <%= form.select :academic_year,
                                    options_for_select((AcademicYear.all).to_a.map{ |val| [val.name,val.id] }) %>
                                </li>
                                <li class="breadcrumb-item"><%= form.submit "Search Cohort", class: "student-list-seach", data: { turbo: false }%></li>

                            </ol>
                        <% end %>
                    </nav>
                    <!-- Table with stripped rows -->
                    <div class= "table-responsive" >


                    <table class="table datatable students-listing py-0  ">
                        <thead>
                        <tr>
                            <th>
                             No
                            </th>
                            <th>
                             First Name(s)
                            </th>
                            <th>Surname</th>
                            <th>ID No.</th>
                            <th data-type="date" data-format="YYYY/DD/MM">Date of Birth</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody >
                            <% @students.each_with_index do |student, index| %>
                                <%= render partial: 'student', locals: { student: student,
                                    index: index,fade_in:false } %>
                            <% end %>
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div><!-- Students list -->


        </div>
    </div><!-- End Left side columns -->

  <!-- Right side columns -->
  <div class="col-lg-4 right-column" >
    <!-- Card  Section -->
        <%= render partial:"members/card_section" , locals: { member: @member, card: @card }  %>
        <%= button_tag "preview card" , id:"preview-card" ,class:"btn btn-primary my-2" %>
    <!-- Card Section -->
  </div>
  <!-- End Right side columns -->
</div>

app/views/student/new_student_list.html.erb
<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Students</a></li>
            <li class="breadcrumb-item active">New list</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

 <% if notice.present? %>
    <p class="py-2 px-3 text-warning" id="notice"><%= notice %></p>
  <% end %>
<div class="row main-section dashboard">
  <!-- Left side columns -->
  <div class="col-lg-6 left-column">
        <div class="row">
        <!-- Revenue Card -->
        <div class="col-xxl-12 col-md-12">
            <div class="info-card revenue-card">
            <div class="target">
                <h2 class= "font-bold " >Please list details</h2>
            </div>
            <div class="card-body">
                <%= form_with url: create_student_list_path, method: :post do |form| %>
                    <div class= "my-5" >
                        <%= form.label :name , 'UNIVERSITY:' %>
                        <%= form.select :location, options_for_select((Location.all).to_a.map{ |val| [val.name,val.id] }) %>
                    </div>

                    <div class= "my-5" >
                        <%= form.label :location , 'ACADEMIC YEAR:' %>
                        <%= form.select :academic_year, options_for_select((AcademicYear.all).to_a.map{ |val| [val.name,val.id] }) %>
                    </div>

                    <div class= "my-5" >
                        <%= form.label :File, 'Student list:' %>
                        <%= form.file_field :file, accept: ".xlsx"  %>
                    </div>
                    <div class= "my-5" >
                        <%= form.label :File, 'Student list:' %>
                        <%= form.file_field :uploaded_file, accept: ".zip" %>
                    </div>

                    <div class= "actions" >
                    <%= form.submit "Upload" %>
                    </div>
                <% end %>
            </div>
            </div>
        </div><!-- End Revenue Card -->
        </div>
   </div>
</div>