config/routes.rb
Rails.application.routes.draw do

  resources :cards

  resources :academic_years
  resources :members
  resources :covers
  resources :locations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  root "members#new"
  get 'student/select-list', to: 'student#index' , as: :select_student_list
  post 'student/select-list', to: 'student#select_student_list', as: :student_list
  get 'student/select-student', to: 'student#index'
  post 'student/select-student', to: 'student#select_student',as: :select_student
  post 'student/mark-printed', to: 'student#mark_printed',as: :mark_printed
  get 'student/new_student_list'
  post 'student/create_student_list', as: :create_student_list

  get 'card', to: 'cards#edit' , as: :edit_card_details
end

app/models/academic_year.rb
class AcademicYear < ApplicationRecord
  validates :name ,presence: true, uniqueness: true
end

app/controllers/academic_years_controller.rb
class AcademicYearsController < ApplicationController
  before_action :set_academic_year, only: %i[ show edit update destroy ]

  # GET /academic_years or /academic_years.json
  def index
    @academic_years = AcademicYear.all
  end

  # GET /academic_years/1 or /academic_years/1.json
  def show
  end

  # GET /academic_years/new
  def new
    @academic_year = AcademicYear.new
  end

  # GET /academic_years/1/edit
  def edit
  end

  # POST /academic_years or /academic_years.json
  def create
    @academic_year = AcademicYear.new(academic_year_params)

    respond_to do |format|
      if @academic_year.save
        format.html { redirect_to academic_year_url(@academic_year), notice: "Academic year was successfully created." }
        format.json { render :show, status: :created, location: @academic_year }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @academic_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /academic_years/1 or /academic_years/1.json
  def update
    respond_to do |format|
      if @academic_year.update(academic_year_params)
        format.html { redirect_to academic_year_url(@academic_year), notice: "Academic year was successfully updated." }
        format.json { render :show, status: :ok, location: @academic_year }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @academic_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /academic_years/1 or /academic_years/1.json
  def destroy
    @academic_year.destroy

    respond_to do |format|
      format.html { redirect_to academic_years_url, notice: "Academic year was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_academic_year
      @academic_year = AcademicYear.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def academic_year_params
      params.require(:academic_year).permit(:name)
    end
end

app/helpers/academic_years_helper.rb
module AcademicYearsHelper
end

app/views/academic_years/_academic_year.html.erb
<div id="<%= dom_id academic_year %>">
  <p>
    <strong>Name:</strong>
    <%= academic_year.name %>
  </p>

</div>

app/views/academic_years/_form.html.erb
<%= form_with(model: academic_year) do |form| %>
  <% if academic_year.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(academic_year.errors.count, "error") %> prohibited this academic_year from being saved:</h2>

      <ul>
        <% academic_year.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/academic_years/edit.html.erb
<h1>Editing academic year</h1>

<%= render "form", academic_year: @academic_year %>

<br>

<div>
  <%= link_to "Show this academic year", @academic_year %> |
  <%= link_to "Back to academic years", academic_years_path %>
</div>

app/views/academic_years/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Academic years</h1>

<div id="academic_years">
  <% @academic_years.each do |academic_year| %>
    <%= render academic_year %>
    <p>
      <%= link_to "Show this academic year", academic_year %>
    </p>
  <% end %>
</div>

<%= link_to "New academic year", new_academic_year_path %>

app/views/academic_years/new.html.erb
<h1>New academic year</h1>

<%= render "form", academic_year: @academic_year %>

<br>

<div>
  <%= link_to "Back to academic years", academic_years_path %>
</div>

app/views/academic_years/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @academic_year %>

<div>
  <%= link_to "Edit this academic year", edit_academic_year_path(@academic_year) %> |
  <%= link_to "Back to academic years", academic_years_path %>

  <%= button_to "Destroy this academic year", @academic_year, method: :delete %>
</div>