config/routes.rb
Rails.application.routes.draw do

  resources :cards

  resources :academic_years
  resources :members
  resources :covers
  resources :locations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  root "members#new"
  get 'student/select-list', to: 'student#index' , as: :select_student_list
  post 'student/select-list', to: 'student#select_student_list', as: :student_list
  get 'student/select-student', to: 'student#index'
  post 'student/select-student', to: 'student#select_student',as: :select_student
  post 'student/mark-printed', to: 'student#mark_printed',as: :mark_printed
  get 'student/new_student_list'
  post 'student/create_student_list', as: :create_student_list

  get 'card', to: 'cards#edit' , as: :edit_card_details
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :cover
  belongs_to :location
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.first()
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:cover_id, :location_id, :date_joined, :date_of_expiry)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>">
  <p>
    <strong>Cover:</strong>
    <%= card.cover_id %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= card.location_id %>
  </p>

  <p>
    <strong>Date joined:</strong>
    <%= card.date_joined %>
  </p>

  <p>
    <strong>Date of expiry:</strong>
    <%= card.date_of_expiry %>
  </p>

</div>

app/views/cards/_form.html.erb
<%= form_with(model: card) do |form| %>
  <% if card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cover_id, style: "display: block" %>
    <%= form.text_field :cover_id %>
  </div>

  <div>
    <%= form.label :location_id, style: "display: block" %>
    <%= form.text_field :location_id %>
  </div>

  <div>
    <%= form.label :date_joined, style: "display: block" %>
    <%= form.date_field :date_joined %>
  </div>

  <div>
    <%= form.label :date_of_expiry, style: "display: block" %>
    <%= form.date_field :date_of_expiry %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Show this card", @card %> |
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cards</h1>

<div id="cards">
  <% @cards.each do |card| %>
    <%= render card %>
    <p>
      <%= link_to "Show this card", card %>
    </p>
  <% end %>
</div>

<%= link_to "New card", new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @card %>

<div>
  <%= link_to "Edit this card", edit_card_path(@card) %> |
  <%= link_to "Back to cards", cards_path %>

  <%= button_to "Destroy this card", @card, method: :delete %>
</div>