config/routes.rb
Rails.application.routes.draw do

  resources :cards

  resources :academic_years
  resources :members
  resources :covers
  resources :locations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  root "members#new"
  get 'student/select-list', to: 'student#index' , as: :select_student_list
  post 'student/select-list', to: 'student#select_student_list', as: :student_list
  get 'student/select-student', to: 'student#index'
  post 'student/select-student', to: 'student#select_student',as: :select_student
  post 'student/mark-printed', to: 'student#mark_printed',as: :mark_printed
  get 'student/new_student_list'
  post 'student/create_student_list', as: :create_student_list

  get 'card', to: 'cards#edit' , as: :edit_card_details
end

app/models/member.rb
class Member < ApplicationRecord

  validates :first_name , :last_name,:membership_number, :date_of_birth, presence: true
  validates :membership_number , uniqueness: true

  belongs_to :cover
  belongs_to :location

  attr_accessor :logo_crop_x,:logo_crop_y, :logo_crop_h,:logo_crop_w

  include ImageUploader::Attachment(:image)
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]
  before_action :set_card, only: %i[new show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    binding.b
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:membership_number ,:first_name, :last_name, :date_of_birth, :date_joined, :cover_id, :location_id, :image)
    end

    def set_card
      @card = Card.first()
    end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_card_back.html.erb
<div class="section" >
    <div class="back-photo-area">
        <%= image_tag image_path('UnimaLogo.png')   , class: "card-back-photo" %>
    </div>
     <p  class="card-back-first-paragraph" >
        The University of Malawi Medical Scheme
    </p>
    <p  class="card-back-second-paragraph" >
        Membership card
    </p>
    <p  class="card-back-third-paragraph" >
        This card is a virtal part of the scheme's claiming system. Failure<br> to produce the card
        on demand may mean a delay in settling<br>your claims or refusal to provide servcies.
    </p>
    <p  class="card-back-fourth-paragraph" >
       A copy of rules of the scheme will be supplied on application. A copy is already<br> supplied to your
       college for reference. The rules and regulations of<br> the scheme are binding on members.
    </p>
    <p  class="card-back-fifth-paragraph" >
        For enquiries, please contact The Medical Scheme Director <br> P.O Box 278, Zomba, Malawi.
        Tel:+265 01524733 Fax: +265 0152666
    </p>
    <p  class="card-back-sixth-paragraph" >
        This card belongs to UNIMED. If found please return it to the above address or nearest police station
    </p>
</div>

app/views/members/_card_front.html.erb
<div class="section" >

    <h5 class= "card-cover text-uppercase" ><%= card&.cover&.name%> COVER</h5>
    <h6 class= "front-first-paragraph" >
        Always quote the membership number in all correspondence
        with the SCHEME
    </h6>
    <p class= "front-second-paragraph" >
        on claim forms always quote Membership Number <br> and date of birth of patient
    </p>
    <div class="id-number-area">
    <p class="label">Membership <br> Number</p>
    <span>&#10148;</span>

    <input type="text" value=<%=member&.membership_number%> class="id-number-input" disabled>

    </div>
    <div class="profile-row">
        <% if member&.image %>
        <%= image_tag member.image_url  , class: " id-photo" %>
        <% else %>
        <img src="" class="id-photo">
        <% end %>
    <ul class="profile-fields">
        <li class="list-item">
        <h6 class="id-label">Surname  &#x3A;</h6>
        <h6 class="id-value "><%= member&.last_name %></h6>
        </li>
        <li class="list-item">
        <h6 class="id-label ">first name  &#x3A;</h6>
        <h6 class="id-value "><%= member&.first_name %></h6>
        </li>
        <li class="list-item">
        <h6 class="id-label">Date of birth &#x3A;</h6>
        <h6 class="id-value "><%= member&.date_of_birth %></h6>
        </li>
        <li class="list-item">
        <h6 class="id-label">Date Joined  &#x3A;</h6>
        <h6 class="id-value bank-bothic"><%= card&.date_of_expiry %></h6>
        </li>
        <li class="list-item">
        <h6 class="id-label">Date Of Expiry  &#x3A;</h6>
        <h6 class="id-value bank-bothic"><%= card&.date_of_expiry %></h6>
        </li>
        <li class="list-item">
        <h6 class="id-label">Location  &#x3A;</h6>
        <h6 class="id-value bank-bothic"><%= card&.location&.name %></h6>
        </li>
    </ul>
    </div>
    <div class="footer-area">
    <p class="holders-signature">HOLDERS SIGNATURE</p>
    <div class="signature-area">
        <%= image_tag image_path('signature.jpg')   , class: "signature-photo" %>
        <p  class="on-behalf-signature" >
            FOR AND ON BEHALF OF THE SCHEME
        </p>
    </div>
    </div>

</div>

app/views/members/_card_section.html.erb
<article class = "article col-md-10 justify-content-center" id = "card_section">
  <section class = "row-section">
    <%= render partial:"members/card_front" , locals: { member: member, card: card   }  %>
  </section>

  <section class = "row-section">
    <%= render partial:"members/card_back" %>
  </section>
</article>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :membership_number, style: "display: block" %>
    <%= form.text_field :membership_number %>
  </div>
  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.text_field :date_of_birth, placeholder:"dd-mm-yyyy"  %>
  </div>

  <div>
    <%= form.label :date_joined, style: "display: block" %>
    <%= form.date_field :date_joined %>
  </div>
  <div>
    <%= form.label :cover, style: "display: block" %>
    <%= form.text_field :cover_id %>
  </div>
   <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location_id %>
  </div>
   <div>
    <%= form.label :image, style: "display: block " %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>First name:</strong>
    <%= member.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= member.last_name %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= member.date_of_birth %>
  </p>

  <p>
    <strong>Date joined:</strong>
    <%= member.date_joined %>
  </p>

  <p>
    <strong>Cover:</strong>
    <%= member.cover_id %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= member.location_id %>
  </p>
  <p >
    <strong>File :</strong>
    <% if member.image %>
      <%= image_tag member.image_url  , class: "new_user_thumbnail" %>
    <% end %>
  </p>



</div>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member %> |
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/index.html.erb
<div class="row main-section dashboard">

  <!-- Left side columns -->
    <div class="col-lg-7 left-column">
        <div class="row">
        <!-- Revenue Card -->
            <div class="col-md-12">
              <div class="card info-card revenue-card">
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center mb-0">Datatables</h5>
                    <p style="color: green"><%= notice %></p>
                    <h1>Members</h1>
                    <div id="members">
                      <% @members.each do |member| %>
                        <%= render member %>
                        <p>
                          <%= link_to "Show this member", member %>
                        </p>
                      <% end %>
                    </div>

                    <%= link_to "New member", new_member_path %>
                </div>
              </div>
            </div><!-- Students list -->


        </div>
    </div><!-- End Left side columns -->

  <!-- Right side columns -->
  <div class="col-lg-4 right-column" >
    <!-- Card  Section -->
        <%= render partial:"card_section" , locals: { member: @member, card: @card }  %>
        <%= button_tag "preview card" , id:"preview-card" ,class:"btn btn-primary my-2" %>
    <!-- Card Section -->
  </div>
  <!-- End Right side columns -->
</div>

app/views/members/new.html.erb
<div class="row main-section dashboard">

  <!-- Left side columns -->
    <div class="col-lg-7 left-column">
        <div class="row">
        <!-- Revenue Card -->
            <div class="col-md-12">
              <div class="card info-card revenue-card">
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center mb-0">Datatables</h5>
                     <%= render "form", member: @member %>
                </div>
              </div>
            </div><!-- Students list -->


        </div>
    </div><!-- End Left side columns -->

  <!-- Right side columns -->
  <div class="col-lg-4 right-column" >
    <!-- Card  Section -->
        <%= render partial:"card_section" , locals: { member: @member, card: @card }  %>
        <%= button_tag "preview card" , id:"preview-card" ,class:"btn btn-primary my-2" %>
    <!-- Card Section -->
  </div>
  <!-- End Right side columns -->
</div>

app/views/members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member) %> |
  <%= link_to "Back to members", members_path %>

  <%= button_to "Destroy this member", @member, method: :delete %>
</div>